# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    automerged_updates:
      - match:
          update_type: "semver:patch"
        merge_method: "squash"
        merge_when_pipeline_succeeds: true
      - match:
          update_type: "semver:minor"
        merge_method: "squash"
        merge_when_pipeline_succeeds: true

  - package-ecosystem: "npm"
    directory: "cdk/"
    schedule:
      interval: "weekly"
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
    automerged_updates:
      - match:
          update_type: "semver:patch"
        merge_method: "squash"
        merge_when_pipeline_succeeds: true
      - match:
          update_type: "semver:minor"
        merge_method: "squash"
        merge_when_pipeline_succeeds: true

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    automerged_updates:
      - match:
          update_type: "semver:patch"
        merge_method: "squash"
        merge_when_pipeline_succeeds: true
      - match:
          update_type: "semver:minor"
        merge_method: "squash"
        merge_when_pipeline_succeeds: true
