AWSTemplateFormatVersion: 2010-09-09
Description: Organization Conformance Pack for Superwerker Backup

Resources:
  ConfigRuleDynamoDBTable:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: superwerker-backup-enforce-dynamodb-table
      Scope:
        ComplianceResourceTypes:
          - AWS::DynamoDB::Table
      InputParameters:
        tag1Key: superwerker:backup
        tag1Value: daily,none
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS

  ConfigRemediationDynamoDBTable:
    DependsOn: ConfigRuleDynamoDBTable
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: superwerker-backup-enforce-dynamodb-table
      Automatic: true
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60
      TargetId: arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:document/${BackupTagRemediation}
      TargetType: SSM_DOCUMENT
      Parameters:
        ResourceValue:
          ResourceValue:
            Value: "RESOURCE_ID"
        AutomationAssumeRole:
          StaticValue:
            Values:
              - arn:${AWS::Partition}:iam::${AWS::AccountId}:role/SuperwerkerBackupTagsEnforcementRemediationRole # ${AWS::AccountId} is magically replaced with the actual sub-account id (magic by Conformance Pack)
        ResourceType:
          StaticValue:
            Values:
              - AWS::DynamoDB::Table

  ConfigRuleEbsVolume:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: superwerker-backup-enforce-ebs-volume
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Volume
      InputParameters:
        tag1Key: superwerker:backup
        tag1Value: daily,none
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS

  ConfigRemediationEbsVolume:
    DependsOn: ConfigRuleEbsVolume
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: superwerker-backup-enforce-ebs-volume
      Automatic: true
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60
      TargetId: arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:document/${BackupTagRemediation}
      TargetType: SSM_DOCUMENT
      Parameters:
        ResourceValue:
          ResourceValue:
            Value: "RESOURCE_ID"
        AutomationAssumeRole:
          StaticValue:
            Values:
              - arn:${AWS::Partition}:iam::${AWS::AccountId}:role/SuperwerkerBackupTagsEnforcementRemediationRole # ${AWS::AccountId} is magically replaced with the actual sub-account id (magic by Conformance Pack)
        ResourceType:
          StaticValue:
            Values:
              - AWS::EC2::Volume

  ConfigRuleRdsDbInstance:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: superwerker-backup-enforce-rds-instance
      Scope:
        ComplianceResourceTypes:
          - AWS::RDS::DBInstance
      InputParameters:
        tag1Key: superwerker:backup
        tag1Value: daily,none
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS

  ConfigRemediationRdsDbInstance:
    DependsOn: ConfigRuleRdsDbInstance
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: superwerker-backup-enforce-rds-instance
      Automatic: true
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60
      TargetId: arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:document/${BackupTagRemediation}
      TargetType: SSM_DOCUMENT
      Parameters:
        ResourceValue:
          ResourceValue:
            Value: "RESOURCE_ID"
        AutomationAssumeRole:
          StaticValue:
            Values:
              - arn:${AWS::Partition}:iam::${AWS::AccountId}:role/SuperwerkerBackupTagsEnforcementRemediationRole # ${AWS::AccountId} is magically replaced with the actual sub-account id (magic by Conformance Pack)
        ResourceType:
          StaticValue:
            Values:
              - AWS::RDS::DBInstance
