=== Specialized knowledge

This deployment requires a moderate level of familiarity with
AWS services. If you’re new to AWS, see https://aws.amazon.com/getting-started/[Getting Started Resource Center^]
and https://aws.amazon.com/training/[AWS Training and Certification^]. These sites provide materials for learning how to design,
deploy, and operate your infrastructure and applications on the AWS Cloud.

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/specialized_knowledge.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/specialized_knowledge.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

=== AWS account

If you don’t already have an AWS account, create one at https://aws.amazon.com/[https://aws.amazon.com^] by following the on-screen instructions. Part of the sign-up process involves receiving a phone call and entering a PIN using the phone keypad.

Your AWS account is automatically signed up for all AWS services. You are charged only for the services you use.

ifndef::disable_requirements[]
=== Technical requirements

Before you launch the Quick Start, review the following information and ensure that your account is properly configured. Otherwise, deployment might fail.
endif::disable_requirements[]

==== Resource quotas
If necessary, request https://console.aws.amazon.com/servicequotas/home?region=us-east-2#!/[service quota increases^] for the following resources. You might request quota increases to avoid exceeding the default limits for any resources that are shared across multiple deployments. The https://console.aws.amazon.com/servicequotas/home?region=us-east-2#!/[Service Quotas console^] displays your usage and quotas for some aspects of some services. For more information, see https://docs.aws.amazon.com/servicequotas/latest/userguide/intro.html[What is Service Quotas?^] and https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html[AWS service quotas^].

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/service_limits.adoc`**_
++++
<div class="preview_mode">
++++
endif::production_build[]
include::../{specificdir}/service_limits.adoc[]
ifndef::production_build[]
++++
</div>
++++
endif::production_build[]
include::../{generateddir}/services/metadata.adoc[]

ifndef::disable_regions[]
// We can also pull in Regions automatically.
==== Supported Regions

ifdef::template_not_all_regions[]
This deployment includes <service>, which isn’t currently supported in all https://aws.amazon.com/about-aws/global-infrastructure/[AWS Regions^].
endif::template_not_all_regions[]

ifdef::auto_populate_regions[]
The following Regions are currently supported by this Quick Start.
include::../{generateddir}/regions/index.adoc[]
endif::auto_populate_regions[]

ifndef::auto_populate_regions[]

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/regions.adoc`**_
++++
<div id="preview_mode">
++++
endif::production_build[]
include::../{specificdir}/regions.adoc[]
ifndef::production_build[]
++++
</div>
++++
endif::production_build[]

endif::auto_populate_regions[]

TIP: Certain Regions are available on an opt-in basis. For more information, see https://docs.aws.amazon.com/general/latest/gr/rande-manage.html[Managing AWS Regions^].

endif::disable_regions[]
ifdef::template_ec2[]
==== EC2 key pairs
ifndef::production_build[====]
ifndef::production_build[_This section applies only if the Cloudformation templates include EC2 instances._]
ifndef::production_build[====]
Make sure that at least one https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pair^] exists in your AWS account in the Region where you plan to deploy the Quick Start. Make note of the key pair name. You need it during deployment. To create a key pair, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs and Linux instances^].

For testing or proof-of-concept purposes, we recommend creating a new key pair instead of using one that’s already being used by a production instance.
endif::template_ec2[]

==== IAM permissions
//todo: scope of least-privilege
Before launching the Quick Start, you must sign in to the AWS Management Console with IAM permissions for the resources that the templates deploy. The _AdministratorAccess_ managed policy within IAM provides sufficient permissions, although your organization may choose to use a custom policy with more restrictions. For more information, see https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html[AWS managed policies for job functions^].

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/pre-reqs.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/pre-reqs.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

==== Deployment options
ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/deployment_options.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/deployment_options.adoc[]
ifndef::production_build[]
|===
endif::production_build[]
