// If no preperation is required, remove all content from here

==== Prepare your AWS account

Sign in to an AWS account as an administrator using the AWS root user or an AWS Identity and Access Management (IAM) user or role with the _AdministratorAccess_ policy attached. This account must not be a member of an AWS organization.

==== Prepare for the deployment

The {partner-product-short-name} Quick Start works best with a dedicated DNS subdomain to securely handle email inboxes of AWS sub-accounts.

When entering values in to the CloudFormation template, you must provide both a domain (example: mycompany.com) and subdomain (example: aws) names for a DNS zone created by {partner-product-short-name}. The installation provides Name Server (NS) entries for the newly created DNS zone. You must create an NS entry within your DNS provider to delegate the DNS zone (these records are available later in the CloudWatch dashboard). The {partner-product-short-name} installation waits until the delegation is properly configured.
