AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sets up notifications. (qs-1s3rsr7mk)
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E9007

Parameters:
  NotificationsMail:
    Type: String

Outputs:
  NotificationTopic:
    Description: Notification topic ARN for ops center creation events
    Value: !Ref NotificationTopic

Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref NotificationsMail
        Protocol: email

  NotificationOpsItemCreated:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Enable:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ssm
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventName:
                  - CreateOpsItem
                eventSource:
                  - ssm.amazonaws.com
      Handler: index.handler
      Runtime: python3.7
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
      Environment:
        Variables:
          TOPIC_ARN: !Ref NotificationTopic
      InlineCode: !Sub |-
        import boto3
        import json
        import os

        client = boto3.client('sns')

        def handler(event, context):
          response_elements = event['detail']['responseElements']
          id = response_elements.get('OpsItemId', response_elements.get('opsItemId'))
          request_parameters = event['detail']['requestParameters']
          desc = request_parameters.get('Description', request_parameters.get('description'))
          title = request_parameters.get('Title', request_parameters.get('title'))
          assert id and title and desc

          url = "https://${AWS::Region}.console.aws.amazon.com/systems-manager/opsitems/{}".format(id)

          log({
            'desc': desc,
            'event': event,
            'level': 'info',
            'msg': 'Publishing new ops item event from CloudTrail to SNS',
            'title': title,
            'url': url,
          })

          message_title = "New OpsItem: {}".format(title)
          message_body = "{}\n\n{}".format(desc, url)

          client.publish(
            Message=message_body,
            Subject=message_title,
            TopicArn=os.environ['TOPIC_ARN'],
          )

        def log(msg):
          print(json.dumps(msg), flush=True)
