name: AWS Quickstart Release

on:
  workflow_call:
    inputs:
      SUPERWERKER_VERSION:
        required: true
        type: string
    secrets:
      BOT_ACCESS_TOKEN:
        required: true
      RELEASES_AWS_ACCESS_KEY:
        required: true
      RELEASES_AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
    inputs:
      SUPERWERKER_VERSION:
        required: true
        type: string

jobs:
  quickstart:
    runs-on: ubuntu-latest
    steps:
      - name: Clone superwerker-quickstart
        run: git clone https://superwerker-bot:${{ secrets.BOT_ACCESS_TOKEN }}@github.com/superwerker/quickstart-superwerker.git quickstart-superwerker

      - name: Configure Git, email
        run: git config --global user.email "services+github-superwerker-bot@superluminar.io"

      - name: Configure Git, name
        run: git config --global user.name "superwerker-bot"

      - name: sync main branch of fork with upstream
        run: |
          cd quickstart-superwerker \
            && git remote add upstream https://superwerker-bot:${{ secrets.BOT_ACCESS_TOKEN }}@github.com/aws-quickstart/quickstart-superwerker.git \
            && git fetch upstream \
            && git reset --hard upstream/main \
            && git push origin main

      - name: Create a new branch for the release
        run: 'cd quickstart-superwerker && git checkout -b release/${{ inputs.SUPERWERKER_VERSION }}'

      - name: Remove existing CloudFormation templates
        run: rm -rf quickstart-superwerker/templates

      - name: Copy CloudFormation template from release bucket
        run: aws s3 cp s3://superwerker-releases/${{ inputs.SUPERWERKER_VERSION }}/templates/superwerker.template.yaml quickstart-superwerker/templates/
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASES_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASES_AWS_SECRET_ACCESS_KEY }}

      - name: List files
        run: ls -ahl quickstart-superwerker/templates

      - name: Create commit
        run: 'cd quickstart-superwerker && git add templates && git commit -m "release: ${{ inputs.SUPERWERKER_VERSION }}"'

      - name: Push to repository
        run: 'cd quickstart-superwerker && git push -u origin release/${{ inputs.SUPERWERKER_VERSION }}'

      - name: Create Pull Request
        run: |
          curl \
            --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.BOT_ACCESS_TOKEN }}" \
            https://api.github.com/repos/aws-quickstart/quickstart-superwerker/pulls \
            -d '{"head":"superwerker:release/${{ inputs.SUPERWERKER_VERSION }}", "base":"main", "title": "release: ${{ inputs.SUPERWERKER_VERSION }}", "body": "Hey @davmayd @troy-ameigh, please take a look at the most recent release:\n\nhttps://github.com/superwerker/superwerker/releases/tag/v${{ inputs.SUPERWERKER_VERSION }}"}'